fix(db): use DISTINCT instead of GROUP BY to remove duplicates when joining with project's org (#932)
currently,
```
SELECT "events"."created_at","events"."project_id","events"."event_id","events"."destination_id","events"."integration_id","events"."connection_id","events"."trigger_id","events"."event_type","events"."memo","events"."seq","events"."deleted_at" FROM "events" INNER JOIN projects ON projects.org_id = '019400ec-b7c5-780d-9395-3816c9d2f60c' WHERE seq >= 0 AND "events"."deleted_at" IS NULL GROUP BY "event_id" ORDER BY seq desc LIMIT 500
```
gives
```
ERROR:  column "events.created_at" must appear in the GROUP BY clause or be used in an aggregate function
```

this turns it into
```
SELECT DISTINCT "events"."created_at","events"."project_id","events"."event_id","events"."destination_id","events"."integration_id","events"."connection_id","events"."trigger_id","events"."event_type","events"."memo","events"."seq","events"."deleted_at" FROM "events" INNER JOIN projects ON projects.org_id = '019400ec-b7c5-780d-9395-3816c9d2f60c' WHERE seq >= 0 AND "events"."deleted_at" IS NULL ORDER BY seq desc LIMIT 500
```
which works.